#!/usr/bin/env -S deno run --allow-all

import { $, cd, echo, os, path, within } from "zx";

const aspect = import.meta.dirname;

await within(async () => {
  echo`install darkman`;
  await $`
    ghq get https://gitlab.com/WhyNotHugo/darkman.git
  `;
  cd(`${await $`ghq root`}/gitlab.com/WhyNotHugo/darkman`);
  await $`
    make
    make install PREFIX=~/.local/bin
  `;
});

await within(async () => {
  echo`copy files`;
  const target = path.join(os.homedir(), ".local/share/");
  await $`cp -r ${path.join(aspect, "files", "dark-mode.d")} ${target}`;
  await $`cp -r ${path.join(aspect, "files", "light-mode.d")} ${target}`;
});
