#!/usr/bin/env bash
# mise description="Setup website"

set -euxo pipefail

git_url=""
website_location="/var/www/website"

# Loop through arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --git-url)
            git_url="$2"
            shift 2 # shift twice to bypass key and value
            ;;
        *)
            echo "Unknown parameter passed: $1"
            exit 1
            ;;
    esac
done

if test -n "$git_url"; then
    if test ! -d "$website_location"; then
      git clone $git_url $website_location
    fi
    cd $website_location
    git pull origin --rebase

  # build quartz
  cd $website_location
  npm i --ci
  npx quartz build
fi

