[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = ${VPS_PRIVATE_KEY}

PostUp   = iptables -t nat -A PREROUTING -p tcp --dport 8081 -j DNAT --to-destination 10.0.0.2:8081
PostUp   = iptables -A FORWARD -p tcp -d 10.0.0.2 --dport 8081 -j ACCEPT
PostDown = iptables -t nat -D PREROUTING -p tcp --dport 8081 -j DNAT --to-destination 10.0.0.2:8081
PostDown = iptables -D FORWARD -p tcp -d 10.0.0.2 --dport 8081 -j ACCEPT

[Peer]
PublicKey = ${DESKTOP_PUBLIC_KEY}
AllowedIPs = 10.0.0.2/32
