experimental_monorepo_root = true

[monorepo]
config_roots = [
  "aspects/*",
]

[env]
SERVER="hobl.at"
SQUARE_PATH="/home/square"

[settings]
sops.rops = false
experimental = true

[tools]
sops = "latest"
age = "latest"
ghq = "latest"
deno = "2.4"
gomplate = "latest"

[task_config]
includes = [
  "aspects/darkman/aspect.toml",
  "aspects/espanso/aspect.toml",
  "aspects/fonts/aspect.toml",
  "aspects/i3status-rust/aspect.toml",
  "aspects/interception/aspect.toml",
  "aspects/nala/aspect.toml",
  "aspects/nvim/aspect.toml",
  "aspects/server/aspect.toml",
  "aspects/shell/aspect.toml",
  "aspects/systemd/aspect.toml"
]

[tasks."fig:test"]
description = "Run fig tests"
run = "deno test -A"

[tasks."fig:lint"]
description = "Lint fig modules"
run = "deno lint fig/"

[tasks."fig:check"]
description = "Type-check fig modules"
run = "deno check fig"

[tasks."fig:verify"]
description = "Run fig check, lint, and tests"
depends = ["fig:check", "fig:lint", "fig:test"]

[tasks."fig"]
description = "Run all fig:* tasks"
depends = ["fig:*"]

[tasks."aspects:check"]
description = "Type-check fig modules"
run = "deno check aspects/**/*.ts"
