#!/bin/bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils

# Install Bash 4
brew install bash

# Install wget with IRI support
brew install wget --enable-iri

# Install more recent versions of some OS X tools
brew tap homebrew/dupes
brew install homebrew/dupes/grep

# Install everything else
brew install ack
brew install git
brew install rename
brew install tree
brew install node
brew install z
brew install macvim --override-system-vim
brew install graphicsmagick
brew install webkit2png
brew install python
brew install trash

# Remove outdated versions from the cellar
brew cleanup

# install some node dependencies
#npm install jshint -g
#npm install -g git://github.com/ramitos/jsctags.git
