#!/bin/bash

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

if ! command -v mise &> /dev/null; then
  echo "No 'mise' executable found. Install with 'curl https://mise.run | sh'"
  exit 1
fi

# TODO use aspects
# ln -s $(pwd)/aspects $(pwd)/.mise/tasks

# enable tasks
mise settings set experimental true

echo "The following mise tasks are available:"
mise t

