#!/usr/bin/env bash
# mise description="Setup Caddy Server"
# mise alias="caddy"

set -euxo pipefail

mkdir -m 770 -p "$SQUARE_PATH/data/share/caddy"

if ! command -v caddy &>/dev/null; then
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y caddy
fi

cp "${MISE_CONFIG_ROOT}/caddy.service" /etc/systemd/system/caddy.service

systemctl daemon-reload
systemctl enable caddy.service
systemctl restart caddy.service
