#!/usr/bin/env bash

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

# go version
echo "root: $root"

cp ${root}/test/test.service /etc/systemd/system/test.service

systemctl daemon-reload
systemctl enable test.service
systemctl restart test.service
