[tasks."update"]
description = "update homebrew"
run = "deno run --allow-all index.ts update"

[tasks."brew"]
description = "brew install"
depends = [":update"]
run = "deno run --allow-all index.ts brew"

[tasks."cleanup"]
description = "cleanup homebrew"
run = "deno run --allow-all index.ts cleanup"

[tasks.default]
description = "Setup homebrew"
depends = [":brew"]
depends_post = [":cleanup"]
