
set nocompatible                " choose no compatibility with legacy vi
syntax enable
set encoding=utf-8
set showcmd                     " display incomplete commands
filetype plugin indent on       " load file type plugins + indentation
call pathogen#infect()

set background=dark
color molokai

set number "Show lines numbers

set ruler "Display current cursor position in lower right corner.
set showcmd "Show command in bottom right portion of the screen
set laststatus=2 "Always show the status line
set showmatch " Show matching of: () [] {}
set mousehide "Hide mouse when typing

set autoread " Auto read when file is changed
set hidden " Hide buffers, rather than close them

set autowrite "Write the old file out when switching between files.

set wildmenu " More useful command-line completion
set wildmode=list:longest,full "Auto-completion menu


"" Formatting
set autoindent " Indent at the same level as previous line
set copyindent
set smartindent
set smarttab

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

let mapleader="," 

"" No needs for backups, I have Git for that
set noswapfile 
set nobackup


"" NerdTree
let NERDTreeChDirMode = 1
let NERDTreeWinSize=20
let NERDTreeShowHidden=1

:noremap ,n :NERDTreeToggle<CR>

