#!/usr/bin/env bash

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

cp ${MISE_CONFIG_ROOT}/files/.* ~/
echo "Copies dotfiles."

mise install --yes
