#!/usr/bin/env bash

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

shopt -s dotglob nullglob
for src in "${MISE_CONFIG_ROOT}/files/"*; do
  cp -a "$src" "$HOME/$(basename "$src")"
done

echo "Installed aspect dotfiles into \$HOME."

mise install --yes
