
[settings]
experimental = true

[tools]
ghq = "latest"
go = "1.20"

[tasks.setup]
description = 'Setup mise'
run = """
#!/usr/bin/env bash
set -euxo pipefail
# copy global mise config
cp ${root}/.mise/files/default-npm-packages ~/.default-npm-packages
# install mise tools
mise install --yes
"""
