#!/bin/bash
# mise description="Creates symlinks in $HOME to the dotfiles in this rep"

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

if ! command -v stow &> /dev/null; then
  echo "No 'stow' executable found."
  exit 1
fi

echo "Creating symlinks"
stow -v dots


# based on https://github.com/necolas/dotfiles/blob/master/bin/dotfiles
# 1. download dotfiles if not exist
# 2. source helper files
# 3. check print help text
# 4. check flags (--no-packages, --no-sync)
# 5. check for build-essentials
# 6. check homebrew
# 7. check git
# 8. Initialize the git repository if it's missing
# 9. Conditionally (--no-sync) sync with the remote repository
# 10. Conditionally (--no-packages) Install and update packages
# 11. Ask before potentially overwriting files (linking)
# 12. link dotfiles and source bashrc


# https://github.com/sapegin/dotfiles/blob/master/bin/dotfiles
