#!/bin/bash

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

export HOMEBREW_AUTO_UPDATE_SECS=3600

kernel_name=`uname`
brew=$([ kernel_name == 'Dargin' ] && echo 'Homebrew' || echo 'Linuxbrew')

if ! command -v brew &> /dev/null; then
  echo "Install $brew https://brew.sh/"
  exit 1
else
  echo "$brew already installed ..."
fi

# Make sure we’re using the latest Brew
brew update

# Upgrade any already-installed formular
brew upgrade

# General packages.
brew install coreutils # Install GNU core utilities (those that come with OS X are outdated)
brew install findutils # Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install wget
brew install tmux
brew install git
brew instal git-delta # https://github.com/dandavison/delta -- A viewer for git and diff output
brew install fzf
brew install eza # https://github.com/eza-community/eza
brew install ripgrep # Ripgrep - fzf/vim is configured to use this
brew install procs # A modern replacement for ps written in Rust -- https://github.com/dalance/procs
brew install sd # https://github.com/chmln/sd -- Intuitive find & replace CLI (sed alternative)
brew install dust # https://github.com/bootandy/dust -- A more intuitive version of du in rust
brew install tokei # Count your code, quickly.
brew install tealdeer # https://github.com/dbrgn/tealdeer -- A very fast implementation of tldr in Rust.
brew install bandwhich # https://github.com/imsnif/bandwhich -- Terminal bandwidth utilization tool
brew install grex # https://github.com/pemistahl/grex -- A command-line tool and library for generating regular expressions from user-provided test cases
brew install zoxide # https://github.com/ajeetdsouza/zoxide -- A smarter cd command. Supports all major shells.
brew install nushell # https://github.com/nushell/nushell -- A new type of shell
brew install lf # https://github.com/gokcehan/lf -- list-files, ranger replacement
brew install bottom # https://github.com/ClementTsang/bottom -- Yet another cross-platform graphical process/system monitor.
brew install python
brew install python3
brew install tree
brew install xclip
brew install wmctrl
brew install httpie # https://github.com/httpie/httpie -- Modern, user-friendly command-line HTTP client for the API era
brew install fish
brew install github/gh/gh
brew install asciinema # https://github.com/asciinema/asciinema -- Terminal session recorder video_camera
brew install translate-shell
brew install mise # asdf alternative
brew install glow
brew install exercism
brew install stylua
brew install todo-txt
brew install tig # https://github.com/jonas/tig -- Text-mode interface for git
brew install sops # https://github.com/mozilla/sops -- Simple and flexible tool for managing secrets
brew install fx # https://github.com/antonmedv/fx/ Command-line tool and terminal JSON viewer fire
brew install jq # https://github.com/stedolan/jq -- https://github.com/stedolan/jq
# brew install harelba/q/q # http://harelba.github.io/q/ -- q - Run SQL directly on CSV or TSV files
# brew tap kaplanelad/tap && brew install shellfirm
brew install loc # https://github.com/cgag/loc -- Count lines of code quickly.
brew install croc # https://github.com/schollz/croc -- Easily and securely send things from one computer to another
brew install massren # https://github.com/laurent22/massren -- easily rename multiple files using your text editor
brew install xsv # https://github.com/BurntSushi/xsv -- A fast CSV command line toolkit written in Rust.
brew install yatharth/misc/wolframalpha-cli # https://github.com/yatharth/wolframalpha-cli -- query wolframalpha from cli `wa`
brew install slides # https://github.com/maaslalani/slides
brew install efm-langserver # https://github.com/mattn/efm-langserver
brew install ghq #https://github.com/x-motemen/ghq
# brew install thefuck # https://github.com/nvbn/thefuck
brew install entr # https://github.com/eradman/entr
brew install hexyl # https://github.com/sharkdp/hexyl
brew install duf # https://github.com/muesli/duf -- Disk Usage/Free Utility - a better 'df' alternative
brew install dog # https://github.com/ogham/dog
brew install scmpuff # https://github.com/mroth/scmpuff
brew install direnv # https://github.com/direnv/direnv
brew install egoist/tap/dum # https://github.com/egoist/dum
brew install pnpm # https://pnpm.io/
brew install bash-snippets # https://github.com/alexanderepstein/Bash-Snippets
brew install gron # https://github.com/tomnomnom/gron
brew install scc # https://github.com/boyter/scc
brew install lorem
brew install gum
brew install timewarrior # https://github.com/GothenburgBitFactory/timewarrior
brew install noborus/tap/trdsql # https://github.com/noborus/trdsql -- CLI tool that can execute SQL queries on CSV, LTSV, JSON and TBLN. Can output to various formats.
brew install tig # https://jonas.github.io/tig/
brew install age # https://github.com/FiloSottile/age
brew install khal # https://github.com/pimutils/khal
brew install vdirsyncer # https://github.com/pimutils/vdirsyncer
brew install charmbracelet/tap/mods #https://github.com/charmbracelet/mods/
brew install youtube-dl # https://github.com/ytdl-org/youtube-dl
brew install glab # https://gitlab.com/gitlab-org/cli
brew install zx # https://google.github.io/zx/setup
brew install starship # https://github.com/starship/starship

# Remove outdated versions from the cellar
brew cleanup
