#!/bin/bash

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail


if ! command -v nala &> /dev/null; then
  echo "Install nala https://gitlab.com/volian/nala/-/wikis/Installation"
  exit 1
else
  echo "nala already installed ..."
fi

sudo nala install -y build-essential procps curl file git # homebrew essentials
sudo nala install -y stow
sudo nala install -y i3
sudo nala install -y feh

