#!/bin/bash
# mise description="Install and update packages via nala, a apt wrapper"

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

if ! command -v nala &> /dev/null; then
  echo "Install nala https://gitlab.com/volian/nala/-/wikis/Installation"
  exit 1
else
  echo "nala already installed ..."
fi

sudo nala install -y cmake pkg-config # to build tools (alacritty)
sudo nala install -y build-essential procps curl file git # homebrew essentials
sudo nala install -y stow # to symlink dotfiles
sudo nala install -y i3 # window manager
sudo nala install -y feh # to manage background image
sudo nala install -y nautilus-dropbox # to manage background image
sudo nala install -y zathura # a document viewer
sudo nala install -y cryptsetup steghide # used for tomb
sudo nala install -y pass # https://www.passwordstore.org/
sudo nala install -y autorandr # https://github.com/phillipberndt/autorandr
sudo nala install -y flameshot # https://github.com/flameshot-org/flameshot
