#!/usr/bin/env bash
# mise description="Install Evolu Relay Server"

mkdir -m 770 -p "$RELAY_DATA"

echo "Installing dependencies..."
mise exec -- npm install

cp ${root}/evolu-relay.service /etc/systemd/system/evolu-relay.service

sudo systemctl daemon-reload
sudo systemctl enable evolu-relay.service
sudo systemctl restart evolu-relay.service
