[env]
FNOX_AGE_KEY_FILE = "~/.config/mise/age.txt"
SOPS_AGE_KEY_FILE = "~/.config/mise/age.txt"

[tools]
deno = "2.5.1"
golang = "1.20"
node = "22.16.0"
lua = "latest"
python = "3.11"
pipx = 'latest'
bun = "latest"
ruby = "latest"
rust = "latest"
zig = "v0.15.2"
usage = "latest"
"github:anomalyco/opencode" = "latest"
age = "latest"
fnox = "latest"
pitchfork = "latest"

[settings]
experimental = false
idiomatic_version_file_enable_tools = []
color_theme = "base16"
