icons_format = "{icon}"


[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome4"

[[block]]
block = "pomodoro"
notify_cmd = "notify-send '{msg}'"
blocking_cmd = false

[[block]]
block = "battery"
interval = 5
format = " $icon $percentage "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "notify"
format = " $icon {$paused{Off}|On} "

[[block]]
block = "xrandr"
format = " $icon $brightness $resolution "
interval = 5

[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 50
click_temp = 3500

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid|Wired connection} "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%Y.%m.%d %H:%M' ) "
