default_provider = "pass"

[providers]
age = { type = "age", recipients = ["age1hyzsy9lcheqjjcwpvs6nvfxu6ns30tg8we7vxhnvc7wl3r0v496sqk5jv9"] }

[providers.pass]
type = "password-store"
prefix = "fnox/"

[secrets]
OPENROUTER_API_KEY= { provider = "pass", value = "OPENROUTER_API_KEY" }
FIREWORKS_API_KEY= { provider = "pass", value = "FIREWORKS_API_KEY" }
OPENAI_API_KEY= { provider = "pass", value = "OPENAI_API_KEY" }
GITHUB_TOKEN= { provider = "pass", value = "GITHUB_TOKEN" }
EXA_API_KEY= { provider = "pass", value = "EXA_API_KEY" }
TEICH_RELAY_URL= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucUlOK3hUNmJxQWZRejZha0RaVkxPNUh1akU3Zmh3c20reTJsdHhjSVhVCmdTdEZaTXo1ZGlqVjNNNmpCV1hybFBzL0w4SGFHWTNqS0QwVFM1OWl0cEEKLT4gN2BUQiM9Ky1ncmVhc2UKc0R0ejlpQnZBY3c2Q0cybjRIWG5PL2Foc0dXY0tRc0xDSUVta2I0K3RJZHh2bG0xMkVqeE01d2w2OWVUVTRaVQpuMng5YlZmaHQ0UUhMSlRGdnFGRDlQNnZzR1A2L0lQT1RMcjJsM0pNMnNKSG5XdGJOTWtaCi0tLSAvQTd5M0x2dWRpZzZiY2NYcmRpT3hTNm13cTd3bE1DMm95U0xyUWRkRzA0CsA3vHIlaimkQ6MGHzEdVW6yUzi99ntuZIri9aC0A/JXV1aXLanba7EcRV57sF42GG0AESQz" }
TEICH_LOG_LEVEL= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMY0ViRjhJVkRzNFRJSFdaR2xMU2dMQW0zL0QraVB4eWF4OEp5dGUwK1JFCm9pY3FycHIwSTR4N0tLNUUvZzBNM3M0ZE14YW1nYUlyRE16MTZPZk56WlkKLT4gQi9eMlgtZ3JlYXNlIGBaQVosIDZde1lXclAgNEp0I3ZfXyBxCmkzb3R4ZVFLY0VtSjByUXlWT2htQ1E5dDhaSjNaSnIvQUJ3bWlZRlZPQXhvL0xublRoZwotLS0gbktQeTU4WTEwTFFPdzZBeFVjeWNwUlAvUlpSRW9aV1JwVkNIRis1S2pQSQot3bx6zrpWMjO6IPIhGIlJKdckM1JBMDo8S0aPiIg/VH879GQd" }
TEICH_WATCH_DIR= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dWtaNTBoZlNBM2pZeXBKVGlHRnVTRnZNQnA3MHZLZloxNnZ4L1pWV0U0Cm9FQjlXbWxDb0JuQ1BZN2dpOEd2YkxDTXBXQlhDaXM3SUdkM2tpaDArVDAKLT4gMS1ncmVhc2UgKWdTIGptU0dLCksvekw5OGZlCi0tLSB1MTlic2pycmlCVHdkL3F0TUhvNzFPWTNSU3ZuNzM3UVVSeEExa0xHajJrCteJTVHaeUo+TYZ9N4Y/oK/H+szgqW+upoFcPG0k0POFiRpd3XJadwfa69y1eFIy4qI8b+tZfsds" }
