#!/usr/bin/env bash

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

pitchfork restart test

if systemctl is-enabled test.service &>/dev/null; then
  systemctl disable --now test.service
  rm -f /etc/systemd/system/test.service
  systemctl daemon-reload
fi
