fish_add_path ~/.dotfiles/bin
fish_add_path ~/.dotfiles/bin/wm
fish_add_path ~/.bin
fish_add_path ~/Dropbox/.bin
fish_add_path ~/.local/bin
fish_add_path ~/.cargo/bin
fish_add_path ~/go/bin
fish_add_path ~/opt/nvim/squashfs-root/usr/bin
fish_add_path ~/opt/espanso/squashfs-root/usr/bin
