#!/usr/bin/env bash
# mise depends=["setup:rclone"]

set -euxo pipefail

res=$(crontab -l | grep backup || echo "")
if [[ $res == "" ]]; then
  (crontab -l 2>/dev/null; echo "9 3 * * * cd /home/square/aspects; mise run backup;") | crontab -
fi

rclone copy /home/square/data remote:backup/server --progress
