#!/bin/bash
# mise description="Upgrade packages via nala"

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

if ! command -v nala >/dev/null; then
  echo "Install nala https://gitlab.com/volian/nala/-/wikis/Installation" >&2
  exit 1
fi

sudo nala update
sudo nala upgrade -y
