#!/usr/bin/env bash

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

DIR="$(dirname "$(realpath "$0")")"
FILES_DIR="$DIR/files"
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

cp -r "$FILES_DIR/srv/square/aspects" "$TEMP_DIR/aspects"
find "$TEMP_DIR" -type f -exec sed -i "s|\${SQUARE_PATH}|$SQUARE_PATH|g" {} +
find "$TEMP_DIR" -type f -exec sed -i "s|{SQUARE_PATH}|$SQUARE_PATH|g" {} +

rsync --delete --quiet -rpt --compress --chown=:square "$TEMP_DIR/aspects/" $SERVER:"$SQUARE_PATH/aspects/"

sshcmd="
# symlink aspects to mise tasks
mkdir -p /etc/mise/tasks
find \"$SQUARE_PATH\"/aspects -maxdepth 1 -type f -exec ln -sf {} /etc/mise/tasks \;

> /etc/mise/tasks.toml
find \"$SQUARE_PATH\"/aspects -maxdepth 2 -type f -name \"tasks.toml\" -exec cat {} >> /etc/mise/tasks.toml \;

echo \"The following mise tasks are available:\" && mise t

if systemctl is-active pitchfork.service &>/dev/null; then
  systemctl restart pitchfork.service
fi
"

ssh $SERVER "bash -l -c '$sshcmd'"
