#!/bin/bash

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

fishPath="$(command -v fish || true)"

if [[ -z "$fishPath" ]]; then
  echo "warn: fish not found in PATH, skipping"
  exit 0
fi

if ! grep -q fish /etc/shells; then
  echo "$fishPath" | sudo tee -a /etc/shells
fi

chsh -s "$fishPath"

if [[ -n "${DATA_DIR:-}" ]]; then
  mkdir -p ~/.local/share/fish "${DATA_BACKUP}"
  fishHistory=~/.local/share/fish/fish_history
  timestamp=${DATA_BACKUP}/fish-history.$(date +'%Y.%m.%d-%S')
  if [[ -f "$fishHistory" ]] && ! [[ -L "$fishHistory" ]]; then
    mv "$fishHistory" "$timestamp"
  fi
  if ! [[ -L "$fishHistory" ]]; then
    ln -sf "$DATA_DIR/fish_history" "$fishHistory"
    if [[ -f "$timestamp" ]]; then
      cat "$timestamp" > "$DATA_DIR/fish_history"
    fi
  fi
fi
