[env]
SOFT_SERVE_DATA_PATH = "{{env.SQUARE_PATH}}/data/share/soft-serve"
# SOFT_SERVE_CONFIG_LOCATION = "{{config_root}}"
SOFT_SERVE_INITIAL_ADMIN_KEYS = "{{env.PUBLIC_KEY  | default(value='none') }}"
KEY_NAME="id_rsa"
KEY_DIR="{{env.SQUARE_PATH}}/.ssh"

[tools]
go = "1.21"

[tasks.default]
file = './default'

[tasks."user"]
hide = true
description = 'Create local user'
file = './user'

[task_config]
includes = [
  "tasks.toml"
]

