
[env]
SITE_PATH = "{{env.SQUARE_PATH}}/data/share/website"

[tasks.default]
file = './default'

[tasks.personal-website]
run = 'mise r default --repo personal-website'

[tasks.thepopupschool]
run = 'mise r default --repo thepopupschool'
