#!/usr/bin/env bash

set -euxo pipefail

# set write permission for group
mkdir -m 770 -p $SQUARE_PATH/data/share/goatcounter

if ! [ -x "$(command -v goatcounter)" ]; then
  ghq get https://github.com/arp242/goatcounter
  cd $SQUARE_PATH/data/share/ghq/github.com/arp242/goatcounter
  go build -ldflags="-X zgo.at/goatcounter/v2.Version=$(git log -n1 --format='%h_%cI')" ./cmd/goatcounter
  mkdir -p ${MISE_CONFIG_ROOT}/bin
  cp ./goatcounter ${MISE_CONFIG_ROOT}/bin/goatcounter
fi


cp ${MISE_CONFIG_ROOT}/goatcounter.service /etc/systemd/system/goatcounter.service

sudo systemctl daemon-reload
sudo systemctl enable goatcounter.service
sudo systemctl restart goatcounter.service
