--ozone-platform=wayland
--ozone-platform-hint=wayland
--enable-features=TouchpadOverscrollHistoryNavigation
--load-extension=/home/hobl/.local/share/omarchy/default/chromium/extensions/copy-url,/home/hobl/.local/share/chromium/extensions/site-search
