# https://starship.rs/

[character]
success_symbol = "[➜](bold #b8bb26)"
error_symbol = "[➜](bold #fb4934)"
vicmd_symbol = "[🆅](bold #a89984)"

[package]
# symbol = ""
# disabled = true

[nodejs]
# disabled = true

[custom.sandbox]
when = "env | grep -E '^IN_SANDBOX=1$'"
format = "[sandboxed](bold red) "
disabled = false
