# https://espanso.org

matches:
  - trigger: "e.."
    replace: "samuel.hobl@gmail.com"

  - trigger: "mfg"
    replace: "Mit freundlichen Grüßen"

  - triggers: ["teh", "thee"]
    replace: "the"
    word: true

  - trigger: "dont"
    replace: "don't"
    word: true

  - trigger: "cant"
    replace: "can't"
    word: true

  - trigger: "consc"
    replace: "consciousness"
    word: true

  - trigger: ").."
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"

toggle_key: OFF
show_notifications: false
# backspace_delay: 0
# inject_delay: 0
enable_passive: true
passive_key: CTRL
# backend: Clipboard
