#!/bin/bash

if [ -x "$(command -v asdf)" ]; then
  asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
  asdf plugin-add python https://github.com/tuvistavie/asdf-python.git
  asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
  asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  asdf plugin-add rust https://github.com/code-lever/asdf-rust.git
fi

