#!/bin/bash

kernel_name=`uname`
brew=$([ kernel_name == 'Dargin' ] && echo 'Homebrew' || echo 'Linuxbrew')

# Check for brew and install if needed

which brew
if [[ $? != 0 ]] ; then
  echo "Installing $brew ..."
  yes | bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
else
  echo "$brew already installed ..."
fi

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formular
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils

# Install Bash 4
brew install bash

# Install wget
brew install wget

# neovim
brew install neovim --HEAD

# fzf
brew install fzf
yes | $(brew --prefix)/opt/fzf/install

# tmux
brew install tmux

# git
brew install cdiff
brew install git
brew install diff-so-fancy

# rust
brew install fd
brew install bat
brew install starship
brew install exa
brew install ripgrep # Ripgrep - fzf/vim is configured to use this
brew install procs
brew install sd
brew install dust
brew install tokei
brew install tealdeer
brew install bandwhich
brew install grex
brew install zoxide
brew install nushell
brew install lf # list-files, ranger replacement
brew tap clementtsang/bottom
brew install bottom

# Install everything else
brew install tree
brew install python
brew install xclip
brew install wmctrl
brew install httpie
brew install fish
brew install github/gh/gh
brew install asciinema
brew install translate-shell
brew install asdf
brew install glow
brew install exercism
brew install todo-txt
brew install tig
brew install sops
brew install fx # https://github.com/antonmedv/fx/
brew install jq # https://stedolan.github.io/
brew install q # http://harelba.github.io/q/
brew install loc # https://github.com/cgag/loc

# Remove outdated versions from the cellar
brew cleanup
