#!/bin/bash

echo "Installing nvm ..."
if [ ! -s "$NVM_DIR/nvm.sh" ] ; then
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | zsh
  source "$HOME/.nvm/nvm.sh"
  echo "Installing node $node_install_version ..."
  nvm install node
  nvm alias default node
else
  echo "nvm already installed ..."
fi

echo "Installing npm global packages ..."

npm i -g --quiet http-server
npm i -g --quiet imageoptim-cli
npm i -g --quiet nodemon
npm i -g --quiet npm-check
npm i -g --quiet npmlist
npm i -g --quiet tern
npm i -g --quiet ntl
npm i -g --quiet trymodule
npm i -g --quiet pageres-cli
npm i -g --quiet lerna

echo "Installing yarn ..."

curl -o- -L https://yarnpkg.com/install.sh | bash
