#!/bin/bash

symlink_dotfile() {
  ln -sfv $(realpath $1) "$HOME/.$1"
}

symlink() {
  ln -sfv $(realpath $1) "$HOME/$1"
}

symlink_xdg() {
  ln -sfv $(realpath $1) "$HOME/.config/$1"
}

echo "Creating symlinks ..."

pushd ./dots

symlink_dotfile alacritty.yml
symlink_dotfile tern-project
symlink_dotfile todo.cfg
symlink_dotfile Xresources
symlink_dotfile gitconfig
symlink_dotfile gitignore_global
symlink_dotfile git-completion.bash
symlink_dotfile inputrc
symlink_dotfile xmobarrc
symlink_dotfile bash_profile
symlink_dotfile bashrc
symlink_dotfile tmux.conf
symlink_dotfile vimrc
symlink_dotfile default-npm-packages
symlink_xdg starship.toml

ln -sfv $(grealpath xmonad.hs) "$HOME/.xmonad/xmonad.hs"

# Directories

symlink bin
