#!/bin/bash

symlink_dotfile() {
  ln -sfv $(realpath $1) "$HOME/.$1"
}

symlink() {
  ln -sfv $(realpath $1) "$HOME/$1"
}

echo "Creating symlinks ..."

pushd ./dots

symlink_dotfile alacritty.yml
symlink_dotfile tern-project
symlink_dotfile todo.cfg
symlink_dotfile Xresources
symlink_dotfile gitconfig
symlink_dotfile gitignore_global
symlink_dotfile inputrc
symlink_dotfile xmobar.conf
symlink_dotfile xmonad.hs
symlink_dotfile bash_profile
symlink_dotfile bashrc
symlink_dotfile tmux.conf
# symlink_dotfile vimrc

# Directories

symlink bin
