#!/bin/bash

# install dependencies
sudo apt-get install gcc make pkg-config libx11-dev libxtst-dev libxi-dev

which xcape
if [[ $? != 0 ]] ; then
  # install xcape
  git clone https://github.com/alols/xcape.git 
  cd xcape
  make
  sudo make install
  rm -rf ../xcape
fi
