#!/usr/bin/env bash
# mise description="Setup Caddy Server"

set -euxo pipefail


if ! [ -x "$(command -v caddy)" ]; then
  ghq get https://github.com/caddyserver/caddy.git
  cd ~/ghq/github.com/caddyserver/caddy

  go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
  xcaddy build
  cp ./caddy /usr/local/bin/caddy

  # id -u caddy &>/dev/null || useradd --system \
  #   --gid square \
  #   --create-home \
  #   --home-dir /var/lib/caddy \
  #   --shell /usr/sbin/nologin \
  #   --comment "Caddy web server" \
  #   caddy
fi

mkdir -p /etc/caddy && cp ${root}/Caddyfile /etc/caddy/Caddyfile
cp ${root}/caddy.service /etc/systemd/system/caddy.service

systemctl daemon-reload
systemctl enable caddy.service
systemctl restart caddy.service
