#!/usr/bin/env bash
# mise description="Setup Caddy Server"
# mise alias="caddy"

set -euxo pipefail

# set write permission for group
mkdir -m 770 -p $SQUARE_PATH/data/share/caddy

if ! [ -x "$(command -v caddy)" ]; then
  ghq get https://github.com/caddyserver/caddy.git
  cd ~/ghq/github.com/caddyserver/caddy

  go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
  xcaddy build
  mkdir -p ${root}/bin
  cp ./caddy ${root}/bin/caddy
fi

# mkdir -p /etc/caddy && cp ${root}/Caddyfile /etc/caddy/Caddyfile
cp ${root}/caddy.service /etc/systemd/system/caddy.service

systemctl daemon-reload
systemctl enable caddy.service
systemctl restart caddy.service
