#
# █████╗ ██╗      █████╗  ██████╗██████╗  █████╗ ████████╗████████╗██╗   ██╗██╗   ██╗███╗   ███╗██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██╔══██╗╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝╚██╗ ██╔╝████╗ ████║██║
# ███████║██║     ███████║██║     ██████╔╝███████║   ██║      ██║    ╚████╔╝  ╚████╔╝ ██╔████╔██║██║
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██╔══██║   ██║      ██║     ╚██╔╝    ╚██╔╝  ██║╚██╔╝██║██║
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║  ██║   ██║      ██║      ██║██╗   ██║   ██║ ╚═╝ ██║███████╗
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝      ╚═╝      ╚═╝╚═╝   ╚═╝   ╚═╝     ╚═╝╚══════╝
#

import = [
    "~/.config/alacritty/themes/themes/gruvbox_light.toml"
]

[font]
normal = { family = "JetBrainsMono", style = "Medium" }
bold = { family = "JetBrainsMono", style = "Bold" }
italic = { family = "JetBrainsMono", style = "Italic" }
size = 12
