#!/bin/bash
# mise description="Set up firmware updates via fwupd"

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

sudo fwupdmgr refresh
sudo fwupdmgr update
