[tasks."preflight"]
description = "Verify environment and prepare pacman"
file = 'preflight'

[tasks."packages"]
description = "Install packages via pacman and set up AUR environment (paru)"
depends = [":preflight"]
file = 'packages'

[tasks."firewall"]
description = "Set up ufw firewall"
depends = [":packages"]
file = 'firewall'

[tasks."firmware"]
description = "Update firmware via fwupd"
depends = [":packages"]
file = 'firmware'

[tasks.default]
description = "Run all aur tasks"
depends = [":packages", ":firewall"]
