#!/usr/bin/env bash

set -e

mkdir -m 770 -p $SITE_PATH

cd $SITE_PATH

git clone --local "$SQUARE_PATH/data/share/soft-serve/repos/memex.git" "repo" || echo "Repo already cloned"

(cd "$MISE_CONFIG_ROOT/../soft-serve" && \
  mise run soft-serve:webhooks:create --repo memex --id generate-anki \
) || echo "Webhook already exists (or could not be created), continuing…" >&2

cd $SITE_PATH/repo

mise install

git reset --hard HEAD
git pull origin --rebase

cp ${MISE_CONFIG_ROOT}/memex.service /etc/systemd/system/memex.service

sudo systemctl daemon-reload
sudo systemctl enable memex.service
sudo systemctl restart memex.service
