[env]
SITE_PATH = "{{env.SQUARE_PATH}}/data/share/memex"
_.path = [
    "./bin",
]

[tools]
go = "1.22"
python = "3.11"

[tasks.default]
file = './default'

[tasks.start]
file = './start'

[tasks."generate:anki"]
file = './generate-anki'
