[env]
SITE_PATH = "{{env.SQUARE_PATH}}/data/share/memex"
_.path = [
    "./bin",
]

[tools]
bun = "1.2.4"
python = "3.11"

[tasks.default]
file = './default'

[tasks.start]
run = '''
#!/usr/bin/env bash

set -e

cd $SITE_PATH/repo
mise r build-index
mise r serve --port 8088
'''
