[env]
SQUARE_PATH = "{SQUARE_PATH}"
GOCACHE = "{SQUARE_PATH}/data/cache/go"

[settings]
experimental = true

[tools]
ghq = "latest"
python = "3.11"
node = "22"
"npm:zx" = "latest"
pitchfork = "2.26.0"
