[env]
GOCACHE = "/home/square/data/cache/go"

[settings]
experimental = true

[tools]
ghq = "latest"
python = "3.11"
node = "20.5.1"
"npm:zx" = "latest"

[task_config]
includes = [
  "tasks",
  "tasks.toml"
]
