#!/usr/bin/env -S deno run --allow-all

import { $, cd, fs, os, spinner } from "zx";
import { Readable } from "node:stream";
import { finished } from "node:stream/promises";

await spinner("make ~/opt/espanso", async () => {
  await $`mkdir -p ${os.homedir()}/opt/espanso`;
});

await spinner("download Espanso appimage", async () => {
  const stream = fs.createWriteStream(
    `${os.homedir()}/opt/espanso/espanso.appimage`,
  );
  const { body } = await fetch(
    "https://github.com/espanso/espanso/releases/download/v2.2.1/Espanso-X11.AppImage",
  );
  await finished(Readable.fromWeb(body).pipe(stream));
});

await spinner("make Espanso appimage executable", async () => {
  await $`chmod 0755 ${os.homedir()}/opt/espanso/espanso.appimage`;
});

await spinner("extract Espanoe appimage files", async () => {
  cd(`${os.homedir()}/opt/espanso/`);
  await $`${os.homedir()}/opt/espanso/espanso.appimage --appimage-extract`;
});
