#!/usr/bin/env -S deno run --allow-all

import { assert, command, fetch, file, init, path } from "fig";

init(import.meta.dirname);

const NERD_FONTS_VERSION = "v3.4.0";

const home = path.home.toString();
const fontsDir = `${home}/.local/share/fonts`;

const dirs = await command("mkdir", ["-p", fontsDir, `${home}/opt`]);
assert.result(dirs);

async function installNerdFont(name: string) {
  const marker = `${fontsDir}/.${name}-${NERD_FONTS_VERSION}`;
  if (await Deno.stat(marker).then(() => true).catch(() => false)) return;

  await command("bash", ["-c", `rm -f ${fontsDir}/${name}*.ttf ${fontsDir}/.${name}-v*`]);

  const zip = `${home}/opt/${name}.zip`;
  const extractDir = `${home}/opt/${name}`;

  const dl = await fetch({
    url:
      `https://github.com/ryanoasis/nerd-fonts/releases/download/${NERD_FONTS_VERSION}/${name}.zip`,
    dest: zip,
    encoding: null,
  });
  assert.result(dl);

  const unzip = await command("unzip", ["-o", zip, "-d", extractDir]);
  assert.result(unzip);

  const rm = await command("rm", [zip]);
  assert.result(rm);

  const cp = await command("bash", [
    "-c",
    `cp ${extractDir}/*.ttf ${fontsDir}/`,
  ]);
  assert.result(cp);

  await command("fc-cache", ["-f"]);

  await Deno.writeTextFile(marker, "");
}

await installNerdFont("JetBrainsMono");
await installNerdFont("Noto");

const fontconfig = await file({
  force: true,
  path: `${home}/.config/fontconfig/fonts.conf`,
  src: path.aspect.join("files", ".config", "fontconfig", "fonts.conf")
    .toString(),
  state: "link",
});
assert.result(fontconfig);
