#!/usr/bin/env -S deno run --allow-all

import { assert, command, fetch, init, path } from "fig";

init(import.meta.dirname);

const home = path.home.toString();
const zip = `${home}/opt/JetBrainsMono.zip`;
const extractDir = `${home}/opt/JetBrainsMono`;
const fontsDir = `${home}/.local/share/fonts`;

const dirs = await command("mkdir", ["-p", fontsDir, `${home}/opt`]);
assert.result(dirs);

const installed = [...Deno.readDirSync(fontsDir)].some((e) =>
  e.name.startsWith("JetBrainsMono")
);

if (!installed) {
  const dl = await fetch({
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip",
    dest: zip,
    encoding: null,
  });
  assert.result(dl);

  const unzip = await command("unzip", ["-o", zip, "-d", extractDir]);
  assert.result(unzip);

  const rm = await command("rm", [zip]);
  assert.result(rm);

  const cp = await command("bash", ["-c", `cp ${extractDir}/*.ttf ${fontsDir}/`]);
  assert.result(cp);

  const cache = await command("fc-cache", ["-f", "-v"]);
  assert.result(cache);
}
