#!/usr/bin/env bash

trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

mkdir -p {SQUARE_PATH}/data/share/rss-bridge

cp "${MISE_CONFIG_ROOT}/config.ini.php" {SQUARE_PATH}/data/share/rss-bridge/config.ini.php

docker compose pull
docker compose up -d
